const settingsActionTypes = {
  TOGGLE_COPIED: 'TOGGLE_COPIED',
  ADD_CROSSHAIR: 'ADD_CROSSHAIR',
  TOGGLE_SAVED: 'TOGGLE_SAVED',
  ADD_SETTINGS: 'ADD_SETTINGS',
  REMOVE_SETTINGS: 'REMOVE_SETTINGS',
  REMOVE_CROSSHAIR: 'REMOVE_CROSSHAIR'
}

export default settingsActionTypes;